### ISSUE TITLE
really bad search results for "isced"

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/tools#19]
A search for "**isced**" results in 17 variables within the pairfam study. However the variable https://paneldata.org/variables/126911 with
- name "**isced**13"
- variable label "**ISCED**-1997-Classification"
- concept: _pgen_pg**isced**, labeled with "**ISCED**-1997-Classification"

is not found.

**Comment by mhebing** [comment]
The old search engine always looks for entire words (e.g. "isced13") and not parts of it (e.g. "isced" in "isced13").

I'm currently re-implementing the search engine to deal with this kind of problem...
