### ISSUE TITLE
Update instrument's interface in DoR

### ISSUE THREAD

**Issue by mhebing** [ddionrails/tools#29]
- [x] Intervieweranweisungen fehlen.
- [x] Darstellung von nicht-cat-Antwortoptionen (bin, chr,int) nicht schön.
- [x] Link, der das concept nutzt fehlt
- [x] Navigationsbuttons im Fragebogen (Frage vor, Frage zurück) fehlt
- [x] Sprachumschaltung fehlt
- [x] Übersicht über den Fragebogen (https://ddionrails.soep.de/soep-core/inst/soep-core-2014-pe) ist sehr uninformativ. Zumindest bei unseren Metadaten ist nicht zu erwarten, dass ein Label genutzt wird. Anreißer mit Fragetext wäre gut. Die Spalten study und instrument sind da überflüssig.

**Comment by mhebing** [comment]
Beispiel 1: https://ddionrails.soep.de/soep-is/inst/soep-is-2014-f/q22

1. Ich bin nicht glücklich mit dem großen "Question q22" und zwar aus mehreren Gründen.
  - Als Überschrift hat das zu wenig informativ, hat einen zu technischen Charakter und ist dabei gleichzeitig zu groß. Alternativvorschlag im Anhang.
  - In den gelieferten Metadaten heißt die question "Q22", so wird das auch im Filter (vgl. Beispiel in dieser Frage) verwendet und in den Debug-Informationen steht das auch dreimal (als number, name und question). Was wird hinter der "Question"-Überschrift angezeigt, und warum muss das lower-case sein? Für mich ist Q22 der Inhalt einer case-sensitiven Schlüsselvariable und bin nicht glücklich, dass die beim Import irgendwo verändert wird. (Ich könnte damit leben, wenn die Schreibweise erhalten, aber nicht mehr case-sensitiv ist.)
2. Ich glaube, es entspricht eher der Logik, wenn die Filterbox über dem Fragetext angezeigt wird.
3. Abgesehen davon, dass ich kein Label einer Frage pflegen würde, sollte der m.E. zweisprachig sein.
4. Was wird hinter "Text:" in der Infobox angezeigt? Leere Felder, wie auch "Description:" sollten gar nicht angezeigt werden.
5. Der Fragebogenname ist für mich die einzige hilfreiche Information in der Infobox. Die würde ich nach oben stellen.
6. Variables: Als Information über Variablen würde ich (in dieser Reihenfolge) anzeigen: Name des Datensatzes, Name der Variablen, Label. Also etwa: "h: hlf0080 - other costs included in rent", ggfs. mit entsprechenden Tooltipps und Links. (Das Label sollte auch in der richtigen Sprache angezeigt werden.)
7. Ähnlich beim concept, hier bin ich mir nicht sicher, ob wir den concept-Namen überhaupt zeigen wollen, tendiere aber etwas dazu. Also auch hier concept-Name und Label anzeigen, ggfs. auch in der richtigen Sprache.

---

Beispiel 2: https://ddionrails.soep.de/soep-is/inst/soep-is-2014-f/q26

1. "Response scale: int" ist maximal lieblos und technizistisch.
2. Man sieht auch wieder dass der Filter besser über der Frage aufgehoben wäre.

---

Beispiel 3: https://ddionrails.soep.de/soep-is/inst/soep-is-2014-f/q3201

1. Das ist - soweit ich es sehe - die einzige Situation, wo die Zahlenwerte der Antwortoptionen gezeigt werden.

---

Beispiel 4: https://ddionrails.soep.de/soep-is/inst/soep-is-2014-f/q3301

1. Die Reihenfolge hat sich gegenüber den Metadaten geändert! Auch hier: https://ddionrails.soep.de/soep-is/inst/soep-is-2014-f/q3201
2. "Response scale: bin" ist ebenfalls lieblos und technizistisch. Wie bei Beispiel 3 müsste da eine Tabelle gebaut werden.

---

Beispiel 5:

https://ddionrails.soep.de/soep-is/data/h/hlf0017

1. Grafik?
2. Überschrift: der Variablenname sollte in die Überschrift. M.E. kann das "[variable]" weg.
3. Name des Datensatzes sollte prominenter angezeigt werden, vielleicht auch in der Überschrift, vgl. Beispiel 1, Anmerkung 6.
4. Bei Study sollte m.E. das Label angezeigt werden.

---

Beispiel 6: https://ddionrails.soep.de/concept/hm09

Ich bin dem "Related concept" von Beispiel 1 gefolgt.

1. Unvermittelt stoße ich auf soep-core-Treffer. (Kann man extrem schnell wegfiltern mit "soep-is" in der Searchbox, aber m.E. wäre eine Begrenzung auf den entsprechenden Namespace, wenn man von dieser Richtung kommt, eine gute Idee.
2. Titelvorschlag: Name - label, also "hm09 - Other Costs Included In Rent". Die Description einfach hinschreiben, wenn sie existiert, ohne "Description".
3. Unterüberschrift "Variables" ist falsch, muss abstrakter sein, etwa "Related Objects". Würden da auch die Topics angezeigt?
4. In die Spalte Study sollte m.E. das Label rein.
5. Spaltenüberschrift "Title" sollte m.E. "Label" heißen.

---

Beispiel 7: https://ddionrails.soep.de/soep-is/inst/soep-is-2014-f

1. Ich weiß nicht, ob ich da überhaput eine Sortierung anbieten würde. Zuerst sollte aber die Fragenummer kommen und als "Name" würde ich den auch nicht verstehen.
2. Ich vermute, Du zeigst da das Label an - dann sollte auch die Spalte zu heißen. (Falls die Frage angezeigt wird, was ich besser fände, dann "Text" als Spaltenüberschrift.)
3. An anderen Stellen beginnt die Sort-Variable bei 0.

---

Beispiel 8: https://ddionrails.soep.de/soep-is#instruments

1. Was ist das für eine ID?
2. Gibt es da kein Jahr, nach dem man sinvvoller sortieren könnte und wollte?

---

Grundsätzlich zur Suche in den Tabellen:

Die geht immer flott. Ich würde aber "Find as you type" davor schreiben oder "Fast search", um das von der Suche im Kopf abzugrenzen. (Auch "Search here:" oder "Search these results:")

---

Grundsätzlich zur Überschrift:

Bei Fragen ein invertiertes ?, bei Variablen ein invertiertes V und bei Concepts ein invertiertes C könnte Orientierung bieten, ohne zu dominant zu sein.


Grundsätzliches zu Identifikatoren:

Welches sind die jeweils und welche Eigenschaften sollen sie haben?

**Comment by mhebing** [comment]
![question_mockup](https://cloud.githubusercontent.com/assets/905115/19553290/eb52fe86-96b3-11e6-8cf6-3d39fa49d567.png)

**Comment by mhebing** [comment]
- [ ] Wollen wir die Zahlenwerte für Antwortoptionen angeben?

**Comment by jgoebel** [comment]
Question in filter Anweisung klickbar machen

**Comment by mhebing** [comment]
@kwenzig Ich kann mit allen Rückmeldungen was anfangen, nur mit dem "maximal lieblos und technizistisch" in Bezug auf die Antwortskalen tue ich mir noch schwer. Kannst Du mir da vielleicht bitte noch eine Anregung schicken, was man da besser machen könnte? Geht es um die graphische Darstellung oder die Text innerhalb des Felds oder beides?

**Comment by kwenzig** [comment]
Beides. Der Text im Feld macht m.E. nicht klar, dass hier eine Eingabe zu erwarten wäre und die Platzierung des input-Elements unter dem Fragetext hat auch nicht zur Klärung beigetragen.
![input](https://cloud.githubusercontent.com/assets/6614820/19656057/a44c2666-9a1e-11e6-97ca-c6e2449c7797.PNG)
