### ISSUE TITLE
Fehlermeldung bei basket ohne Studie

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/tools#50]
Es ist  möglich, einen Basket ohne Angabe einer Studie anzulegen. Dann erhält man jedoch eine hässliche Fehlermeldung (https://data.soep.de/workspace/baskets/12).
Möglicher workaround: default soep-core setzen, besser Auswahl erzwingen.

**Comment by mhebing** [comment]
Ist programmiert, geht noch diese Woche online
