### ISSUE TITLE
Fehlleitung durch das Augesymbol

### ISSUE THREAD

**Issue by kwenzig** [ddionrails/tools#73]
- Suchergebnis von yp0101
- Klick auf Auge-Symbol vom letzten Treffer ( [yp0101] Satisfaction With Health
- Variable in study: soep-core | dataset: yp | period: 2008 | analysis unit: p)
- Overlay wird angezeigt: This is a variable with the ID 50892
- Klick auf show more: https://paneldata.org/concept/yp0101
- keine Variable von soep-core wird mehr angezeigt

**Comment by mhebing** [comment]
Danke für die Rückmeldung!

**Comment by mhebing** [comment]
Behoben, geht mit den nächsten Update online
