### ISSUE TITLE
Probleme mit verschiedenen R Versionen

### ISSUE THREAD

**Issue by mhebing** [ddionrails/tools#86]
Leider gibt es da gleich zu Beginn Probleme bei der Erstellung des balanced design und bei der Auswahl der Privathaushalte, da R $pop und $netto als Faktoren speichert und damit die Bedingungen nicht abgerufen werden können und somit am Ende ein Datensatz ohne Beobachtungen rauskommt. Ich dachte, das Problem schnell über as.numeric lösen zu können, es ist aber komplexer, da R andere values zu den einzelnen Ausprägungen vergeben hat, weshalb dann Quatsch dabei raus kommt. Ich schicke dir mal den Auszug aus dem Skript mit

```R
### LOAD [H|P]PFAD ###

pfad <- read.dta(file.path(path_in, "ppfad.dta"))
pfad <- pfad[ , c("hhnr", "persnr", "sex", "gebjahr", "psample","yhhnr", "ynetto", "ypop")]

### [UN]BALANCED ###
pfad <- with(pfad, pfad[ (ynetto >= 10 & ynetto < 20) , ]) #funktioniert nicht, da als Faktoren abgelegt. as.numeric geht nicht, da andere values assigned wurden *levels(pfad$ynetto)

### PRIVATE HOUSEHOLDS ###
pfad <- with(pfad, pfad[ (ypop == 1 | ypop == 2), ]) #funktioniert nicht, da als Faktoren abgelegt. as.numeric geht nicht, da andere values assigned wurden *levels(pfad$ypop)
```

**Comment by mhebing** [comment]
Leider gibt es da gleich zu Beginn Probleme bei der Erstellung des balanced design und bei der Auswahl der Privathaushalte, da R $pop und $netto als Faktoren speichert und damit die Bedingungen nicht abgerufen werden können und somit am Ende ein Datensatz ohne Beobachtungen rauskommt. Ich dachte, das Problem schnell über as.numeric lösen zu können, es ist aber komplexer, da R andere values zu den einzelnen Ausprägungen vergeben hat, weshalb dann Quatsch dabei raus kommt. Ich schicke dir mal den Auszug aus dem Skript mit

```R
### LOAD [H|P]PFAD ###

pfad <- read.dta(file.path(path_in, "ppfad.dta"))
pfad <- pfad[ , c("hhnr", "persnr", "sex", "gebjahr", "psample","yhhnr", "ynetto", "ypop")]

### [UN]BALANCED ###
pfad <- with(pfad, pfad[ (ynetto >= 10 & ynetto < 20) , ]) #funktioniert nicht, da als Faktoren abgelegt. as.numeric geht nicht, da andere values assigned wurden *levels(pfad$ynetto)

### PRIVATE HOUSEHOLDS ###
pfad <- with(pfad, pfad[ (ypop == 1 | ypop == 2), ]) #funktioniert nicht, da als Faktoren abgelegt. as.numeric geht nicht, da andere values assigned wurden *levels(pfad$ypop)
```

**Comment by mhebing** [comment]
@jgoebel

**Comment by lreiber** [comment]
Hallo, 
ich kenne zwei Lösungswege, von denen ich Nummer eins besser finde:

1. Solution, add convert.factors = F  to read.dta13() -> includes real numbers as integers, but labels are missing. get labels if needed with  get.label.name() from readstata13
``` r
library(dplyr)
library(readstata13)
  
#### 1. Solution Example ####
  ### LOAD [H|P]PFAD ###
  pfad <- read.dta13(paste0(path_in,"ppfad.dta"), convert.factors = F) %>% 
    select(hhnr, persnr, sex, gebjahr, psample, yhhnr, ynetto, ypop) %>% 
    filter(ynetto >= 10, ynetto <20,     # (un)balanced
           ypop %in% c(1,2)                    # private households
           )

  # get value labels if needed
 ( labtab <- get.label(pfad, "ynetto")) # if value labels for ynetto are needed
```
2. Solution, recover original codes from converted factor with get.origin.codes() from readstata13
```
#### 2. Solution Example ####
  ### LOAD [H|P]PFAD ###
  pfad2 <- read.dta13(paste0(path_in,"ppfad.dta")) %>%
    select(hhnr, persnr, sex, gebjahr, psample, yhhnr, ynetto, ypop) 
  
  # get original codes
  labtab <- get.label(pfad2, "ynetto")
  pfad2$ynetto <- get.origin.codes(pfad2$ynetto, labtab)
  
  labtab <- get.label(pfad2, "ypop")
  pfad2$ypop <- get.origin.codes(pfad2$ypop, labtab)
  
  pfad2 <- pfad2 %>% 
    filter(ynetto >= 10, ynetto <20,    # (un)balanced
           ypop %in% c(1,2))                   # private 
```

Liebe Grüße,
Lisa

**Comment by kwenzig** [comment]
Dürfte ein Duplikat von #69 und #70 sein.

**Comment by sjewo** [comment]
I ran into the same problem today. 

If you want to keep the factor labels you might just use a custom function which refers to the codes written into the label like "[1]" in "[1] Realisiertes Haushaltsinterview":
```
ifCode <- function(x, code) x==levels(x)[grep(paste0("^\\[",code,"\\]"), levels(x))]

pfad <- with(pfad, pfad[ ifCode(bfhnetto, 1) | ifCode(vhnetto, 1) | 
                                      ifCode(qhnetto, 1) | ifCode(bahnetto, 1),  ])
```
Maybe I'll add something like that to [readstata13](https://github.com/sjewo/readstata13/) - I plan to expand the toolset for factor values anyway.

**Comment by kwenzig** [comment]
Will be solved, when mhebing/ddionrails2#370 is solved.
