### ISSUE TITLE
Variablen aus soep-core 2016 werden vom Skriptgenerator nicht verarbeitet

### ISSUE THREAD

**Issue by johnny2711** [ddionrails/tools#91]
** * * NOT PROCESSED * * *
* From datasets 'bgp': ['bgp5302', 'bgp7701', 'bgp7901']
* From datasets 'bgpgen': ['bgfamstd', 'labgro16', 'emplst16', 'lfs16', 'bgtatzeit', 'bgvebzeit', 'expft16', 'exppt16', 'bgbilzeit']
* From datasets 'bgpequiv': ['d1110116']

**Comment by kwenzig** [comment]
Will be solved in next version that is already tested. Thanks for this issue!
